### ISSUE TITLE
refute function

### ISSUE THREAD

**Issue by pca2** [lehmannro/assert.sh#17]
Great project, and much needed. Have you ever considered supporting a "refute" function? It would allow you to test that a command returns anything BUT a certain value. Example:

``` bash
#check that $count hasn't been defined as 1
refute "echo $count", 1
```

**Comment by lehmannro** [comment]
I'd traditionally use any of the below constructs for this:

``` shell
assert_raises "echo $count | grep -q 1" 1
assert_raises "test $count -ne 1"
```

I like the simplicity of the current API (stdout or exit code, nothing else.)  I'm happy to add a link to helper libraries (like `stub.sh`) to the README if you ever come up with anything.
