### ISSUE TITLE
Incorrect name in package.json

### ISSUE THREAD

**Issue by adamjc** [lehmannro/assert.sh#26]
Hey dude, GitHub have a dependency management bit, and it's showing up incorrectly due to how it gets information between npm and GitHub. Your `name` in the `package.json` is `assert`, but that's already an npm package, so GitHub is getting super confused. 

Can you remove the name field from your `package.json` file. I'd recommend using `make` or another build tool instead of npm for non-node repos. 

The image below shows that there are repos with your dependency, but actually they are depending on `commonjs-assert`, which is what is actually aliased to that name in NPM.

<img width="738" alt="Screenshot 2019-03-25 at 11 58 50" src="https://user-images.githubusercontent.com/3089372/54918135-616d0700-4ef5-11e9-8ab2-dc4d8437a329.png">

https://www.npmjs.com/package/assert <- this is what you are saying your repo is

Cheers.

**Comment by lehmannro** [comment]
AFAICT this was added in 51d7a0ad as a file for [bpkg](http://www.bpkg.sh), not npm.  I'm not sure why bpkg and npm chose the same format — and maybe that's actually a good thing — but a namespace collision between those two seems wholly inappropriate and nothing I can fix on my side.

**Comment by adamjc** [comment]
Ah, my bad I assumed that package.json was strictly limited to npm packages! Interesting. I'm currently trying to raise an issue with GitHub for them to fix it on their end. Thanks for getting back.
